CREATE TABLE WALLET(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "IS_ACTIVE" BOOLEAN,
    "LAST_UPDATED_AT" TIMESTAMP,
    "BALANCE_AMOUNT" BIGINT,
    "WALLET_ID" VARCHAR(255),
    "WALLET_TYPE" VARCHAR(255),
    "USER_ID" BIGINT
)

CREATE TABLE "ADDRESS"(
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "IS_ACTIVE" BOOLEAN,
    "LAST_UPDATED_AT" TIMESTAMP,
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "STREET_NAME" VARCHAR(255),
    "STREET_NUMBER" VARCHAR(255),
    "ZIP_CODE" VARCHAR(255),
    "USER_ID" BIGINT
)

CREATE TABLE "STAR_WALLET_USER"(
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "IS_ACTIVE" BOOLEAN,
    "LAST_UPDATED_AT" TIMESTAMP,
    "BIRTH_DATE" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "MOBILE_NUMBER" VARCHAR(255),
    "USER_TYPE" VARCHAR(255)
)

CREATE TABLE "WALLET_RECHARGE_DETAILS"(
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "IS_ACTIVE" BOOLEAN,
    "LAST_UPDATED_AT" TIMESTAMP,
    "RECHARGE_DONE_AT" TIMESTAMP,
    "RECHARGE_STATUS" VARCHAR(255),
    "TRANSACTION_ID" BIGINT,
    "WALLET_ID" BIGINT
)

CREATE TABLE "TRANSACTIONS"(
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "IS_ACTIVE" BOOLEAN,
    "LAST_UPDATED_AT" TIMESTAMP,
    "AMOUNT" BIGINT,
    "CURRENCY_TYPE" VARCHAR(255),
    "PAYMENT_MODE" VARCHAR(255),
    "TRANSACTION_CONTEXT_ID" VARCHAR(255),
    "TRANSACTION_STATUS" VARCHAR(255),
    "TRANSACTION_TYPE" VARCHAR(255),
    "PARENT_TRANSACTION_ID" BIGINT,
    "WALLET_ID" BIGINT
)